### ISSUE TITLE
Figure 4

### ISSUE THREAD

**Issue by ljjTYJR** [lif314/GS3LAM#1]
Hi,
It seems we have a very similar figure in the paper:
<img src="https://github.com/user-attachments/assets/46567d29-09f2-4be4-b610-4a14a4004d1f" width=300>

https://arxiv.org/abs/2403.12535

what a coincidence! but we have different solutions to the problem 😃 

BY the way, what software do you use, I think your figure is more pretty than mine.

**Comment by lif314** [comment]
> Hi, It seems we have a very similar figure in the paper: <img alt="" width="300" src="https://private-user-images.githubusercontent.com/35888427/372786943-46567d29-09f2-4be4-b610-4a14a4004d1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMzQwNDMsIm5iZiI6MTcyOTIzMzc0MywicGF0aCI6Ii8zNTg4ODQyNy8zNzI3ODY5NDMtNDY1NjdkMjktMDlmMi00YmU0LWI2MTAtNGExNGE0MDA0ZDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDA2NDIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2NGQxZmM2MzgyZmFjZGRhYTdhZTY3ZTdlMzE0YTMyYjc4OTY5NGE0NzM4MTM3YmU0Mjc4ZjVhMmRkOWU0MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mVxpN95teva4hVEfPlAYuqlwFmQAmzpwaJHgscK7HDk">
> 
> https://arxiv.org/abs/2403.12535
> 
> what a coincidence! but we have different solutions to the problem 😃
> 
> BY the way, what software do you use, I think your figure is more pretty than mine.

Sorry for the late reply; I've been rushing other deadlines. Great minds think alike :smile:. My main observation is that methods like Splatam/Point-SLAM optimize the current frame by selecting co-visible frames to optimize together. However, due to the fast optimization of Gaussian properties, the results in these co-visible areas are often mediocre (see Figure 2). Previous NeRF-based SLAM methods would randomly sample some pixels from keyframes when optimizing the current frame to counteract this overfitting (the forgetting problem in SLAM). My solution is quite simple: randomly sample some previous frames for optimization. This approach is effective for rendering quality, but the tracking quality has decreased 😞. I see your solution is more robust and improves both tracking accuracy and rendering quality; I look forward to seeing your implementation! 😄  Lastly, my figures were just created in PPT, so the GS ellipses appear jagged when exporting to PDF.
